export const quotes = [
    '"Paul’s ability to understand a new company’s business logic is fantastic." - Christopher Jones, CIO at 360 Media Direct',
    '"He has a proven ability to learn existing platforms and systems in a short period of time." - Christopher Jones, CIO at 360 Media Direct ',
    '"He can dissect an established client-facing process while analyzing and redesigning it from the ground up while creating efficiencies that were missing before." - Christopher Jones, CIO at 360 Media Direct ',
    '"His attention to detail for technical documentation and internal project tracking is superior." - Christopher Jones, CIO at 360 Media Direct ',
    '"All topped off by his passion for solution design based on direct interactions with clients." - Christopher Jones, CIO at 360 Media Direct',
    '"He has a level of passion that can’t be taught or externally inspired." - Tom Shawver, CTO at Booksio, 360 Media Direct',
    'If you ask Paul if he knows a language that he hasn’t used yet, you don’t get "no" or "sorry", you get "not yet, but I’ll get a book". - Tom Shawver, CTO at Booksio, 360 Media Direct',
    '"Paul’s approach to clean, encapsulated, testable, well-defined products creates something a team can extend and iterate on over time without massive rewrites or refactors." - Tom Shawver, CTO at Booksio, 360 Media Direct ',
    '"Paul’s the professional who’s going to talk to customers, make a plan, and give you a stable foundation the first time." - Tom Shawver, CTO at Booksio, 360 Media Direct',
    '"Paul works tirelessly to tackle every challenge that gets put in front of him." - Ian Taubin , Business Development and Marketing, 360 Media Direct',
    '"He has always demonstrated that no problem is too big or small to work through." - Ian Taubin , Business Development and Marketing, 360 Media Direct',
    '"His knowledge of business goals and tasks needed to meet and exceed those goals are exceptional." - Ian Taubin , Business Development and Marketing, 360 Media Direct',
    '"He is always willing to chip in wherever help is needed and comes with great ideas on how to improve efficiencies and our clients’ experience." - Meg Finley, Director at Lutheran Settlement House ',
    '"During the short period I worked with Paul at AmerisourceBergen, he was able to demonstrate excellent learning ability and interpersonal skills." - Piush Karmacharya, Lead Software Engineer at Salesforce ',
    '"He was always interested in learning new technologies and is passionate about writing efficient code." - Piush Karmacharya, Lead Software Engineer at Salesforce',
    '"He is very detail oriented on his coding and design and has excellent analytical skills." - Piush Karmacharya, Lead Software Engineer at Salesforce',
    '"Paul is a very driven, dedicated individual." - Mike Altieri, SVP Engineering for Xplor Technologies ',
    '"When approaching a project or task he ensures he knows the full scope and throughly understands the technology top to bottom." - Mike Altieri, SVP Engineering for Xplor Technologies ',
    '"Paul is direct in his communication, honest and loyal." - Mike Altieri, SVP Engineering for Xplor Technologies',
];
